name: (stage) Build, Package, Release
'on':
  # release:
  #   types:
  #     - created
  push:
    branches:
      - stage
env:
  VERSION: null
jobs:

  # test:
  #   runs-on: ubuntu-latest
  #   steps:

  #     - id: containerRegistryLogin
  #       name: Login to Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: https://ghcr.io
  #         username: ruedigerp
  #         password: ${{ secrets.GH_TOKEN }}

  build-image-stage:
    runs-on: ubuntu-latest
    # runs-on: macos-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
  
      - uses: actions/setup-node@v6
        with:
          node-version: 20
          
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: get semversion
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - id: containerRegistryLogin
        name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ruedigerp
          password: ${{ secrets.GH_PACKAGE }}
      
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: . 
          file: Dockerfile-amd64
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ruedigerp/ink-blog.kuepper.nrw:${{ env.VERSION }}
            ghcr.io/ruedigerp/ink-blog.kuepper.nrw:latest
          build-args: |
            VERSION=${{ env.VERSION }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max          


